spring:
  application:
    name: spring-messager-api
  mvc:
    apiversion:
      use:
        header: apiVersion
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  amqp:
    deserialization:
      trust:
        all: true